### ISSUE TITLE
It is suport step/dir interface?? 

### ISSUE THREAD

**Issue by artayasa** [jpdigitalman/Madueke_SimMotion#1]
Hi sir. 
Thank you for ypur great prohect. 
It is posible to used ac servo with step dir?? 
Or pwm cw ccw?? Or analog sir?? Because i have a coustem servo driver with 2000ppr encorder woth step/dir interface. I dont know how do u control the servo by witchone interface. Thank u.

**Comment by jpdigitalman** [comment]
Yes, it uses step / dir in the DSUB connector

Check the DSUB Connector Pins.

(pin 4 is direction+, pin 5 is direction -)
(pint 3 is pulse+, pin 14 is pulse-)

Does not use PWM.

**Comment by artayasa** [comment]
> (pin 4 is direction+, pin 5 is direction -)
> (pint 3 is pulse+, pin 14 is pulse-)

So that mean work with my driver are suport step/dir right?? How about step/rev sir? Already fix or can adjust on the web sir.. 
So its meas suport stepper also sir? If yes i want to try mini with stepper first sir. 
Thank u for your great project🙏

**Comment by jpdigitalman** [comment]
Yes, it uses step / dir. 

yes it supports stepper.

**Comment by artayasa** [comment]
How about other pin like a zero speed, out zero post and etc sir?? Posible not used??? 

And how about step/rev like i have stepper with 1.8deg so its mean 200step/rev sir. Need to spesific step/rev?? 
Because i loking video for ypur project nothing sir on youtube.

**Comment by jpdigitalman** [comment]
Did you check the schematics I provided before asking about other pins? 

 If you want to use 200step/rev motor, you modify the number of steps in code.  

Have you checked out the code to understand how it works?  

 Not sure you understand how stepper motor calibration works. 

Why are you looking video of my project on YouTube? 

I didn't add any video link.

**Comment by artayasa** [comment]
> Did you check the schematics I provided before asking about other pins?
> 
> If you want to use 200step/rev motor, you modify the number of steps in code.
> 
> Have you checked out the code to understand how it works?
> 
> Not sure you understand how stepper motor calibration works.
> 
> Why are you looking video of my project on YouTube?
> 
> I didn't add any video link.

Yes sir thank u, now i understand. Mybe i more easy to understand sir🙏. But realy thank u gor uour great project🙏.
